import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'PL' | 'EN';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  PL: {
    // Header
    'nav.services': 'Usługi',
    'nav.projects': 'Projekty', 
    'nav.about': 'O nas',
    'nav.partnership': 'Zostań partnerem',
    'nav.funding': 'Dofinansowanie',
    'nav.letsTalk': 'Porozmawiajmy',
    'nav.services.title': 'Zobacz nasze usługi',
    'nav.projects.title': 'Zobacz nasze projekty',
    'nav.about.title': 'Dowiedz się o nas więcej',
    'nav.partnership.title': 'Zostań naszym partnerem',
    'nav.funding.title': 'Dowiedz się o dofinansowaniu',
    'nav.letsTalk.title': 'Umów krótką rozmowę',
    'nav.language.title': 'Zmień język na angielski',
    
    // Hero Section
    'hero.title1': 'Tworzymy ',
    'hero.title2': 'nowoczesne',
    'hero.title3': ' rozwiązania cyfrowe dla Twojej firmy — ',
    'hero.title4': 'szybciej',
    'hero.title5': ' i ',
    'hero.title6': 'efektywniej',
    'hero.subtitle': 'Dobieramy technologię do Twoich potrzeb, aby dostarczać produkty cyfrowe nawet 40% szybciej i taniej. Łączymy najnowsze osiągnięcia AI z praktycznymi narzędziami no‑code i low‑code.',
    'hero.apps': 'Aplikacje, strony i sklepy internetowe — ',
    'hero.tailored': 'szyte na miarę',
    'hero.cta': 'ROZPOCZNIJMY ROZMOWĘ',
    'hero.advantage': 'ZDOBĄDŹ PRZEWAGĘ:',
    'hero.faster': 'Szybsze i tańsze wdrożenie',
    'hero.ai': 'Skuteczność dzięki najnowszej technologii',
    'hero.support': 'Ciągła dostępność',
    
    // Services Section
    'services.innovation.title1': 'Innowacyjne',
    'services.innovation.title2': ' technologie,',
    'services.innovation.title3': ' szybszy',
    'services.innovation.title4': ' start Twojego biznesu',
    'services.innovation.subtitle': 'W SpeedCode zawsze wybieramy najefektywniejszą ścieżkę technologiczną, aby dostarczać skalowalne, bezpieczne i wysokowydajne rozwiązania — od MVP i narzędzi szytych na miarę po zaawansowane aplikacje i złożone systemy. To podejście zapewnia naszym klientom co najmniej 40% szybszą efektywność przy równoczesnym zmniejszeniu kosztów.',
    'services.title1': 'Od pomysłu do uruchomienia ',
    'services.title2': '– szybciej, kompleksowo, bez kompromisów',
    'services.subtitle': 'Wykorzystując zaawansowane technologie AI, No-Code/Low-Code, pomagamy Ci efektywnie przekształcać Twój pomysł w pełni funkcjonalne narzędzia szyte na miarę, strony internetowe, sklepy online oraz aplikacje mobilne. Poznaj pełną gamę naszych usług:',
    'services.comprehensive': 'Kompleksowe Wsparcie',
    'services.comprehensive.desc': 'Od analizy biznesowej, warsztatów, brandingu i projektowania UX/UI po rozwój i testowanie aplikacji.',
    'services.web': 'Platformy Webowe',
    'services.web.desc': 'Strony internetowe, sklepy online, CRM\'y, systemy rezerwacji, platformy e-learningowe i rozwiązania job board.',
    'services.mobile': 'Aplikacje Mobilne',
    'services.mobile.desc': 'Kompletne aplikacje mobilne na iOS i Android — dostosowane do celów biznesowych.',
    'services.ai': 'Rozwiązania AI i Automatyzacja',
    'services.ai.desc': 'Spersonalizowane ChatBoty, Generatory, Analizatory oraz Agenci AI.',
    'services.quote': 'Wyceń swój projekt',
    
    // About Section
    'about.title': 'Kim jesteśmy?',
    'about.p1': 'W SpeedCode umożliwiamy zarówno globalnym startupom, drobnym przedsiębiorcom jak i dojrzałym firmom przyspieszenie procesu tworzenia produktów dzięki zaawansowanym platformom no-code/low-code oraz sztucznej inteligencji.',
    'about.p2': 'Wykorzystując platformy no-code/low-code takie jak Bubble, FlutterFlow, Webflow, Xano, Lovable, Bolt.new i inncych, nasi klienci doświadczają płynnego, zwinnego procesu rozwoju, który skutkuje wysokiej jakości produktami cyfrowymi, w tym stronami internetowymi i sklepami online.',
    'about.p3': 'Wierzymy, że rozwój no-code/low-code oraz rozwój AI to remedium na dzisiejsze wyzwania, z którymi mierzą się rozwijające się firmy – szybkie wejście na rynek, walidacja pomysłów, iteracja i pivot z produktem, poprawa efektywności biznesowej.',
    'about.p4': 'Pomagamy firmom osiągnąć swoje cele poprzez dostarczanie zaawansowanych platform i aplikacji w inteligentniejszy sposób - wykorzystując technologię AI, no-code/low-code oraz tworzenie dedykowanych stron internetowych i sklepów e-commerce.',
    'about.values': 'Transparentna, jasna komunikacja i wzajemne zaufanie to fundament naszych wartości. Nie jesteś tylko naszym klientem. Jesteś naszym partnerem.',
    'about.slogan': 'Szybciej, lepiej, taniej!',
    'about.technologies': 'Technologie, których używamy:',
    
    // Contact Section
    'contact.hello': 'Cześć!',
    'contact.subtitle': 'Chciałbym usłyszeć o Twoim projekcie!',
    'contact.response': 'Odpowiemy na Twoją wiadomość w ciągu 24 godzin. Tak, to TAKIE proste!',
    'contact.challenges': '1. Jakie są Twoje główne wyzwania, z którymi możemy Ci pomóc?',
    'contact.challenge.development': 'Rozwój aplikacji',
    'contact.challenge.ux': 'UX/UI',
    'contact.challenge.quality': 'Zapewnienie jakości',
    'contact.challenge.integrations': 'Integracje',
    'contact.challenge.ai': 'Rozwiązania AI',
    'contact.challenge.consulting': 'Konsultacje',
    'contact.budget': '2. Jaki jest Twój budżet?',
    'contact.budget.select': 'Wybierz opcję',
    'contact.nda': '3. Czy potrzebujesz NDA?',
    'contact.details': '4. Uzupełnij szczegóły.',
    'contact.firstName': 'Imię',
    'contact.lastName': 'Nazwisko',
    'contact.email': 'Email',
    'contact.phone': 'Telefon',
    'contact.company': 'Firma',
    'contact.message': 'Opowiedz nam o swoim projekcie...',
    'contact.consent1': 'Wyrażam zgodę na przetwarzanie moich danych osobowych przez SpeedCode sp. z o.o. i oświadczam, że podanie moich danych osobowych jest dobrowolne oraz że zostałem poinformowany o prawie żądania dostępu do moich danych osobowych, ich zmiany i usunięcia.',
    'contact.consent2': 'Wyrażam zgodę na przetwarzanie moich danych osobowych przez SpeedCode sp. z o.o. w celach marketingowych. Wyrażenie zgody jest dobrowolne. Masz prawo do wycofania zgody w dowolnym momencie bez wpływu na zgodność z prawem przetwarzania na podstawie zgody przed jej wycofaniem.',
    'contact.send': 'Wyślij Wiadomość',
    'contact.sending': 'Wysyłanie...',
    'contact.success': 'Dziękujemy! Formularz został wysłany.',
    'contact.success.sub': 'Odezwiemy się w ciągu 24 godzin.',
    'contact.error': 'Ups! Coś poszło nie tak.',
    'contact.error.sub': 'Spróbuj ponownie.',
    'contact.back': 'Wróć do formularza',
    'contact.budgetOptions.small': 'Do 20 000 zł',
    'contact.budgetOptions.medium': '20 000 - 50 000 zł',
    'contact.budgetOptions.large': '50 000 - 100 000 zł',
    'contact.budgetOptions.xlarge': 'Powyżej 100 000 zł',
    'contact.nda.yes': 'TAK',
    'contact.nda.no': 'NIE',
    
    // Case Studies Section
    'casestudies.title': 'Nasi zadowoleni klienci',
    'casestudies.subtitle': 'Dołącz do firm digital-first, które wybrały SpeedCode i przyspieszyły swoją strategię wejścia na rynek!',
    'casestudies.all': 'Wszystko',
    'casestudies.morePhotos': 'więcej zdjęć',
    'casestudies.seeMore': 'Zobacz więcej',
    'casestudies.accelerate': 'Przyspiesz wdrożenia',
    'casestudies.useYourSoftware': 'Korzystaj ze swojego oprogramowania',
    'casestudies.fasterAndCheaper': 'szybciej i taniej',
    'casestudies.createdFaster': 'Tworzone szybciej. Taniej, lepiej i skuteczniej.',
    'casestudies.lowerCosts': 'Niższe koszty utrzymania',
    'casestudies.shorterTime': 'Krótszy time‑to‑market',
    'casestudies.higherQuality': 'Wyższa jakość delivery',
    'casestudies.contactUs': 'SKONTAKTUJ SIĘ Z NAMI',
    'casestudies.virentia.desc': 'Nowoczesny CRM do zarządzania magazynem oraz sprzedażą. zbudowany za pomocą narzędzi no-code.',
    'casestudies.shop.desc': 'Sklep internetowy Virentia Luxuria - tradycyjny design, skorelowany z produktami ziołowymi.',
    'casestudies.bookfinanse.desc': 'Kompleksowe oprogramowanie do obsługi zadań i zarządzania klientem.',
    'casestudies.sessio.desc': 'Aplikacja dla prywatnych gabinetów psychoterapeutycznych do obsługi pacjentów i zarządzania gabinetem - projekt partnerski, obecnie w trakcie budowy.',
    
    // Reviews Section
    'reviews.title': 'Traktujemy naszych klientów jak partnerów',
    'reviews.quote1': 'Wysoka jakość, bardzo szybki czas wykonania.',
    'reviews.quote2': 'Doskonałe zarządzanie projektem, ciekawe propozycje i bardzo szybkie wdrożenie.',
    'reviews.quote3': 'Współpraca ze SpeedCode to czysta przyjemność.',
    
    // Process Section
    'process.innovation.title': 'Innowacja, która napędza efektywność rozwoju',
    'process.innovation.subtitle': 'Łączenie narzędzi AI oraz No-Code/Low-Code odblokowuje najwyższy poziom optymalizacji rozwoju — oszczędzając Twój czas, budżet i zasoby w budowaniu produktów cyfrowych.',
    'process.innovative.approach': 'PODEJŚCIE INNOWACYJNE',
    'process.traditional.approach': 'PODEJŚCIE TRADYCYJNE',
    'process.requirements': 'Analiza wymagań i projektowanie',
    'process.design': 'Design UX/UI',
    'process.implementation': 'Implementacja projektu (frontend & backend)',
    'process.deployment': 'Wdrożenie i testowanie',
    'process.integration': 'Integracja z zewnętrznymi narzędziami',
    'process.management': 'Zarządzanie projektem i koszty komunikacji',
    'process.hourlyRate': 'Stawka godzinowa',
    'process.hourlyRateValue': '250 - 399zł',
    'process.projectTime': 'CZAS REALIZACJI PROJEKTU',
    'process.ourApproach': 'Nasze podejście',
    'process.approach.subtitle': 'Budujemy oprogramowanie używając innowacyjnej kombinacji narzędzi no-code/low-code oraz AI, aby usprawnić proces rozwoju i dostarczyć wysokiej jakości rezultaty. Dzięki silnemu skupieniu na optymalizacji rozwoju, możemy ożywić Twoją ideę bardziej efektywnie niż tradycyjne podejście do rozwoju oprogramowania.',
    'process.highStandards': 'Dostarczamy aplikacje z najwyższymi standardami bezpieczeństwa, użyteczności i wydajności.',
    'process.fasterIteration': 'Wykorzystanie platform no-code/low-code oraz sztucznej inteligencji pozwala nam iterować z Twoim produktem szybciej niż w tradycyjnym podejściu.',
    'process.leanStartup': 'Łącząc nasze zwinne podejście z elastycznością platform no-code, pracujemy z klientami w metodologii lean startup, dzięki czemu możesz szybko zwalidować swoją ideę i sprawdzić potencjał rynkowy.',
    'process.quickStart': 'Szybko rozpoczynamy projekty i zapewniamy płynną realizację, od analizy, UI/UX, rozwoju, testów po wprowadzenie na rynek.',
    'process.howWeWork': 'Jak pracujemy?',
    'process.scope': 'ZAKRES',
    'process.scope.desc': 'Łączymy Twoje pomysły i potrzeby oraz nasze sugestie. Definiujemy cele i skupiamy się na kluczowych funkcjach potrzebnych do rozwoju. Pierwszym krokiem jest przekształcenie idei w produkt.',
    'process.design.title': 'DESIGN',
    'process.design.desc': 'Uzgadniamy zakres prac, przygotowujemy makiety wraz z prototypem, aby potwierdzić, że wszyscy rozumiemy potencjalne ścieżki klientów. Kończymy proces, kiedy upewnimy się, że użytkownik oprogramowania dostanie jak najlepsze rozwiązanie, a Twoja firma dzięki temu zarobi.',
    'process.development': 'ROZWÓJ',
    'process.development.desc': 'Budujemy Twoje oprogramowanie, używając platform no-code/low-code oraz AI, które uznaliśmy za najlepszy możliwy wybór. Jesteś informowany o wszystkich krokach, które podejmujemy.',
    
    // Partnership Section
    'partnership.title1': 'Zostań',
    'partnership.title2': ' naszym ',
    'partnership.title3': 'partnerem',
    'partnership.subtitle': 'Masz pomysł na aplikację, ale brakuje Ci zasobów technicznych? Pracujemy również w modelu partnerskim - Ty przedstawiasz pomysł, my go realizujemy, a razem dzielimy się sukcesem!',
    'partnership.jointPartnership': 'Wspólne partnerstwo',
    'partnership.jointPartnership.desc': 'Nie jesteś tylko klientem - stajesz się naszym partnerem biznesowym w realizacji projektu.',
    'partnership.yourIdea': 'Twój pomysł, nasza realizacja',
    'partnership.yourIdea.desc': 'Przedstawiasz nam swój pomysł na aplikację, a my zajmujemy się kompleksową realizacją.',
    'partnership.sharedProfits': 'Wspólne zyski',
    'partnership.sharedProfits.desc': 'Dzielimy się sukcesem - zyski z aplikacji są dzielone zgodnie z ustalonym modelem partnerskim.',
    'partnership.fullSupport': 'Pełne wsparcie techniczne',
    'partnership.fullSupport.desc': 'Zapewniamy kompletne wsparcie techniczne, rozwój i utrzymanie aplikacji.',
    'partnership.fastMarket': 'Szybkie wejście na rynek',
    'partnership.fastMarket.desc': 'Wykorzystujemy nasze doświadczenie i technologie, aby szybko wprowadzić Twój produkt na rynek.',
    'partnership.strategic': 'Strategiczne podejście',
    'partnership.strategic.desc': 'Razem opracowujemy strategię produktu, model biznesowy i plan rozwoju.',
    'partnership.model.title': 'Jak wygląda model partnerski?',
    'partnership.presentIdea': 'Przedstaw pomysł',
    'partnership.presentIdea.desc': 'Opowiedz nam o swojej idei na aplikację, swojej wizji produktu i grupie docelowej.',
    'partnership.jointAnalysis': 'Wspólna analiza',
    'partnership.jointAnalysis.desc': 'Razem analizujemy potencjał biznesowy, opracowujemy strategię i ustalamy warunki partnerstwa.',
    'partnership.implementation': 'Realizacja i zyski',
    'partnership.implementation.desc': 'Tworzymy aplikację, wprowadzamy ją na rynek i dzielimy się sukcesem według ustalonego modelu.',
    'partnership.ideal': '💼 Idealne dla przedsiębiorców, którzy:',
    'partnership.innovativeIdea': '• Mają innowacyjny pomysł na aplikację',
    'partnership.lackResources': '• Brakuje im zasobów technicznych',
    'partnership.quickMarket': '• Chcą szybko wejść na rynek',
    'partnership.experiencedPartner': '• Szukają doświadczonego partnera technicznego',
    'partnership.shareRisk': '• Chcą dzielić ryzyko i zyski',
    'partnership.strategicSupport': '• Potrzebują wsparcia strategicznego',
    'partnership.cta': 'Porozmawiajmy o partnerstwie',
    
    // Funding Section
    'funding.title': 'Dofinansowanie na rozwój oprogramowania',
    'funding.subtitle': 'Współpracujemy z zaufanym partnerem, który pomaga uzyskać dofinansowanie na aplikacje, strony internetowe, sklepy online i inne rozwiązania cyfrowe.',
    'funding.partner': 'KostroKonsulting Biznes',
    'funding.contact.title': 'Kontakt do partnera',
    'funding.phones': 'Nr tel: +48 516 549 759, +48 799 038 425',
    'funding.fb': 'Profil na Facebooku',
    'funding.note': 'Skontaktuj się, aby sprawdzić możliwości dofinansowania Twojego projektu.',
    
    // Footer
    'footer.description': 'AI software house tworzący dedykowane oprogramowanie dla firm szybciej i efektywniej.',
    'footer.rights': '© 2024 SpeedCode sp. z o.o. Wszelkie prawa zastrzeżone.',
    'footer.services': 'Usługi',
    'footer.webDev': 'Rozwój Stron Web',
    'footer.onlineStores': 'Sklepy Online',
    'footer.mobileApps': 'Aplikacje Mobilne',
    'footer.aiSolutions': 'Rozwiązania AI',
    'footer.nocode': 'No-Code/Low-Code',
    'footer.company': 'Firma',
    'footer.aboutUs': 'O Nas',
    'footer.ourWork': 'Nasze Realizacje',
    'footer.contact': 'Kontakt',
    'footer.madeWith': 'Stworzone z 💙 przez SpeedCode - AI software house'
  },
  EN: {
    // Header
    'nav.services': 'Services',
    'nav.projects': 'Projects',
    'nav.about': 'About',
    'nav.partnership': 'Partnership',
    'nav.funding': 'Funding',
    'nav.letsTalk': 'Let\'s talk',
    'nav.services.title': 'See our services',
    'nav.projects.title': 'See our projects',
    'nav.about.title': 'Learn more about us',
    'nav.partnership.title': 'Become our partner',
    'nav.funding.title': 'Learn about funding',
    'nav.letsTalk.title': 'Schedule a quick call',
    'nav.language.title': 'Switch language to Polish',
    
    // Hero Section
    'hero.title1': 'We create ',
    'hero.title2': 'modern',
    'hero.title3': ' digital solutions for your business — ',
    'hero.title4': 'faster',
    'hero.title5': ' and ',
    'hero.title6': 'more efficiently',
    'hero.subtitle': 'We match technology to your needs to deliver digital products up to 40% faster and cheaper. We combine the latest AI achievements with practical no-code and low-code tools.',
    'hero.apps': 'Applications, websites and online stores — ',
    'hero.tailored': 'tailored to perfection',
    'hero.cta': 'LET\'S START THE CONVERSATION',
    'hero.advantage': 'GET THE ADVANTAGE:',
    'hero.faster': 'Faster and cheaper implementation',
    'hero.ai': 'Effectiveness through cutting-edge technology',
    'hero.support': 'Continuous availability',
    
    // Services Section
    'services.innovation.title1': 'Innovative',
    'services.innovation.title2': ' technologies,',
    'services.innovation.title3': ' faster',
    'services.innovation.title4': ' start for your business',
    'services.innovation.subtitle': 'At SpeedCode, we always choose the most effective technological path to deliver scalable, secure and high-performance solutions — from MVP and custom tools to advanced applications and complex systems. This approach ensures our clients at least 40% faster efficiency while reducing costs.',
    'services.title1': 'From idea to launch ',
    'services.title2': '– faster, comprehensive, without compromises',
    'services.subtitle': 'Using advanced AI, No-Code/Low-Code technologies, we help you efficiently transform your idea into fully functional custom tools, websites, online stores and mobile applications. Discover our full range of services:',
    'services.comprehensive': 'Comprehensive Support',
    'services.comprehensive.desc': 'From business analysis, workshops, branding and UX/UI design to application development and testing.',
    'services.web': 'Web Platforms',
    'services.web.desc': 'Websites, online stores, CRMs, booking systems, e-learning platforms and job board solutions.',
    'services.mobile': 'Mobile Applications',
    'services.mobile.desc': 'Complete mobile applications for iOS and Android — tailored to business objectives.',
    'services.ai': 'AI Solutions and Automation',
    'services.ai.desc': 'Personalized ChatBots, Generators, Analyzers and AI Agents.',
    'services.quote': 'Get a quote for your project',
    
    // About Section
    'about.title': 'Who are we?',
    'about.p1': 'At SpeedCode, we enable both global startups, small entrepreneurs and mature companies to accelerate product development through advanced no-code/low-code platforms and artificial intelligence.',
    'about.p2': 'Using no-code/low-code platforms such as Bubble, FlutterFlow, Webflow, Xano, Lovable, Bolt.new and others, our clients experience a smooth, agile development process that results in high-quality digital products, including websites and online stores.',
    'about.p3': 'We believe that no-code/low-code development and AI development are the remedy for today\'s challenges faced by growing companies – rapid market entry, idea validation, product iteration and pivot, improving business efficiency.',
    'about.p4': 'We help companies achieve their goals by delivering advanced platforms and applications in a smarter way - using AI technology, no-code/low-code and creating dedicated websites and e-commerce stores.',
    'about.values': 'Transparent, clear communication and mutual trust are the foundation of our values. You are not just our client. You are our partner.',
    'about.slogan': 'Faster, better, cheaper!',
    'about.technologies': 'Technologies we use:',
    
    // Contact Section
    'contact.hello': 'Hello!',
    'contact.subtitle': 'I\'d love to hear about your project!',
    'contact.response': 'We\'ll respond to your message within 24 hours. Yes, it\'s THAT simple!',
    'contact.challenges': '1. What are your main challenges we can help you with?',
    'contact.challenge.development': 'Application development',
    'contact.challenge.ux': 'UX/UI',
    'contact.challenge.quality': 'Quality assurance',
    'contact.challenge.integrations': 'Integrations',
    'contact.challenge.ai': 'AI Solutions',
    'contact.challenge.consulting': 'Consulting',
    'contact.budget': '2. What is your budget?',
    'contact.budget.select': 'Select option',
    'contact.nda': '3. Do you need an NDA?',
    'contact.details': '4. Fill in the details.',
    'contact.firstName': 'First Name',
    'contact.lastName': 'Last Name',
    'contact.email': 'Email',
    'contact.phone': 'Phone',
    'contact.company': 'Company',
    'contact.message': 'Tell us about your project...',
    'contact.consent1': 'I consent to the processing of my personal data by SpeedCode sp. z o.o. and declare that providing my personal data is voluntary and that I have been informed about the right to request access to my personal data, their modification and deletion.',
    'contact.consent2': 'I consent to the processing of my personal data by SpeedCode sp. z o.o. for marketing purposes. Giving consent is voluntary. You have the right to withdraw consent at any time without affecting the lawfulness of processing based on consent before its withdrawal.',
    'contact.send': 'Send Message',
    'contact.sending': 'Sending...',
    'contact.success': 'Thank you! Form has been sent.',
    'contact.success.sub': 'We\'ll get back to you within 24 hours.',
    'contact.error': 'Oops! Something went wrong.',
    'contact.error.sub': 'Please try again.',
    'contact.back': 'Back to form',
    'contact.budgetOptions.small': 'Up to $5,000',
    'contact.budgetOptions.medium': '$5,000 - $12,500',
    'contact.budgetOptions.large': '$12,500 - $25,000',
    'contact.budgetOptions.xlarge': 'Over $25,000',
    'contact.nda.yes': 'YES',
    'contact.nda.no': 'NO',
    
    // Case Studies Section
    'casestudies.title': 'Our satisfied clients',
    'casestudies.subtitle': 'Join digital-first companies that chose SpeedCode and accelerated their market entry strategy!',
    'casestudies.all': 'All',
    'casestudies.morePhotos': 'more photos',
    'casestudies.seeMore': 'See more',
    'casestudies.accelerate': 'Accelerate implementations',
    'casestudies.useYourSoftware': 'Use your software',
    'casestudies.fasterAndCheaper': 'faster and cheaper',
    'casestudies.createdFaster': 'Created faster. Cheaper, better and more effectively.',
    'casestudies.lowerCosts': 'Lower maintenance costs',
    'casestudies.shorterTime': 'Shorter time-to-market',
    'casestudies.higherQuality': 'Higher delivery quality',
    'casestudies.contactUs': 'CONTACT US',
    'casestudies.virentia.desc': 'Modern CRM for warehouse and sales management. Built with no-code tools.',
    'casestudies.shop.desc': 'Virentia Luxuria online store - traditional design, correlated with herbal products.',
    'casestudies.bookfinanse.desc': 'Comprehensive software for task management and client management.',
    'casestudies.sessio.desc': 'Application for private psychotherapy practices for patient service and practice management - partner project, currently under construction.',
    
    // Reviews Section
    'reviews.title': 'We treat our clients as partners',
    'reviews.quote1': 'High quality, very fast execution time.',
    'reviews.quote2': 'Excellent project management, interesting proposals and very fast implementation.',
    'reviews.quote3': 'Cooperation with SpeedCode is pure pleasure.',
    
    // Process Section
    'process.innovation.title': 'Innovation that drives development efficiency',
    'process.innovation.subtitle': 'Combining AI tools and No-Code/Low-Code unlocks the highest level of development optimization — saving your time, budget and resources in building digital products.',
    'process.innovative.approach': 'INNOVATIVE APPROACH',
    'process.traditional.approach': 'TRADITIONAL APPROACH',
    'process.requirements': 'Requirements analysis and design',
    'process.design': 'UX/UI Design',
    'process.implementation': 'Project implementation (frontend & backend)',
    'process.deployment': 'Deployment and testing',
    'process.integration': 'Integration with external tools',
    'process.management': 'Project management and communication costs',
    'process.hourlyRate': 'Hourly rate',
    'process.hourlyRateValue': '$65 - 105',
    'process.projectTime': 'PROJECT IMPLEMENTATION TIME',
    'process.ourApproach': 'Our approach',
    'process.approach.subtitle': 'We build software using an innovative combination of no-code/low-code tools and AI to streamline the development process and deliver high-quality results. Thanks to our strong focus on development optimization, we can bring your idea to life more efficiently than traditional software development approaches.',
    'process.highStandards': 'We deliver applications with the highest standards of security, usability and performance.',
    'process.fasterIteration': 'Using no-code/low-code platforms and artificial intelligence allows us to iterate with your product faster than traditional approaches.',
    'process.leanStartup': 'Combining our agile approach with the flexibility of no-code platforms, we work with clients in lean startup methodology, so you can quickly validate your idea and check market potential.',
    'process.quickStart': 'We start projects quickly and ensure smooth execution, from analysis, UI/UX, development, testing to market launch.',
    'process.howWeWork': 'How do we work?',
    'process.scope': 'SCOPE',
    'process.scope.desc': 'We combine your ideas and needs with our suggestions. We define goals and focus on key functions needed for development. The first step is transforming the idea into a product.',
    'process.design.title': 'DESIGN',
    'process.design.desc': 'We agree on the scope of work, prepare mockups with a prototype to confirm that we all understand potential customer paths. We end the process when we make sure that the software user gets the best possible solution, and your company earns from it.',
    'process.development': 'DEVELOPMENT',
    'process.development.desc': 'We build your software using no-code/low-code platforms and AI that we consider the best possible choice. You are informed about all the steps we take.',
    
    // Partnership Section
    'partnership.title1': 'Become',
    'partnership.title2': ' our ',
    'partnership.title3': 'partner',
    'partnership.subtitle': 'Do you have an idea for an application but lack technical resources? We also work in a partnership model - you present the idea, we implement it, and together we share the success!',
    'partnership.jointPartnership': 'Joint partnership',
    'partnership.jointPartnership.desc': 'You are not just a client - you become our business partner in project implementation.',
    'partnership.yourIdea': 'Your idea, our implementation',
    'partnership.yourIdea.desc': 'You present us with your application idea, and we handle comprehensive implementation.',
    'partnership.sharedProfits': 'Shared profits',
    'partnership.sharedProfits.desc': 'We share success - application profits are divided according to the established partnership model.',
    'partnership.fullSupport': 'Full technical support',
    'partnership.fullSupport.desc': 'We provide complete technical support, application development and maintenance.',
    'partnership.fastMarket': 'Fast market entry',
    'partnership.fastMarket.desc': 'We use our experience and technologies to quickly bring your product to market.',
    'partnership.strategic': 'Strategic approach',
    'partnership.strategic.desc': 'Together we develop product strategy, business model and development plan.',
    'partnership.model.title': 'How does the partnership model work?',
    'partnership.presentIdea': 'Present idea',
    'partnership.presentIdea.desc': 'Tell us about your application idea, your product vision and target group.',
    'partnership.jointAnalysis': 'Joint analysis',
    'partnership.jointAnalysis.desc': 'Together we analyze business potential, develop strategy and establish partnership terms.',
    'partnership.implementation': 'Implementation and profits',
    'partnership.implementation.desc': 'We create the application, bring it to market and share success according to the established model.',
    'partnership.ideal': '💼 Perfect for entrepreneurs who:',
    'partnership.innovativeIdea': '• Have an innovative application idea',
    'partnership.lackResources': '• Lack technical resources',
    'partnership.quickMarket': '• Want to quickly enter the market',
    'partnership.experiencedPartner': '• Are looking for an experienced technical partner',
    'partnership.shareRisk': '• Want to share risk and profits',
    'partnership.strategicSupport': '• Need strategic support',
    'partnership.cta': 'Let\'s talk about partnership',
    
    // Funding Section
    'funding.title': 'Funding for software development',
    'funding.subtitle': 'We work with a trusted partner who helps secure funding for applications, websites, online stores and other digital solutions.',
    'funding.partner': 'KostroKonsulting Biznes',
    'funding.contact.title': 'Partner contact',
    'funding.phones': 'Phone: +48 516 549 759, +48 799 038 425',
    'funding.fb': 'Facebook profile',
    'funding.note': 'Get in touch to check funding opportunities for your project.',
    
    // Footer
    'footer.description': 'AI software house creating dedicated software for companies faster and more efficiently.',
    'footer.rights': '© 2024 SpeedCode sp. z o.o. All rights reserved.',
    'footer.services': 'Services',
    'footer.webDev': 'Web Development',
    'footer.onlineStores': 'Online Stores',
    'footer.mobileApps': 'Mobile Applications',
    'footer.aiSolutions': 'AI Solutions',
    'footer.nocode': 'No-Code/Low-Code',
    'footer.company': 'Company',
    'footer.aboutUs': 'About Us',
    'footer.ourWork': 'Our Work',
    'footer.contact': 'Contact',
    'footer.madeWith': 'Made with 💙 by SpeedCode - AI software house'
  }
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('PL');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};